- name: deb
  debug:
    msg: "jeste jave"

- block:
  - name: install jdk
    yum:
      name: "{{java.type}}-{{java.version}}"
  rescue:
    - name: clear yum cache
      command: yum clean all
    - name: install jdk
      yum:
        name: "{{java.type}}-{{java.version}}"
  become: True
